package com.devops.app.service;

import com.devops.app.model.DeploymentRecord;
import com.devops.app.model.ServiceStatus;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("DeploymentService Unit Tests")
class DeploymentServiceTest {

    private DeploymentService deploymentService;

    @BeforeEach
    void setUp() {
        deploymentService = new DeploymentService();
    }

    @Test
    @DisplayName("Should return seeded deployments")
    void testGetAllDeployments() {
        List<DeploymentRecord> records = deploymentService.getAllDeployments();
        assertNotNull(records);
        assertFalse(records.isEmpty());
        assertTrue(records.size() >= 3);
    }

    @Test
    @DisplayName("Should find deployment by existing ID")
    void testGetDeploymentById_Found() {
        Optional<DeploymentRecord> record = deploymentService.getDeploymentById("DEP-1001");
        assertTrue(record.isPresent());
        assertEquals("DevOps-Flow-App", record.get().getServiceName());
        assertEquals("SUCCESS", record.get().getStatus());
    }

    @Test
    @DisplayName("Should return empty when deployment ID is not found")
    void testGetDeploymentById_NotFound() {
        Optional<DeploymentRecord> record = deploymentService.getDeploymentById("DEP-9999");
        assertTrue(record.isEmpty());
    }

    @Test
    @DisplayName("Should record new deployment and generate ID if blank")
    void testRecordDeployment_AutoGeneratedId() {
        DeploymentRecord newRecord = new DeploymentRecord();
        newRecord.setServiceName("DevOps-Flow-App");
        newRecord.setVersion("1.0.1");
        newRecord.setEnvironment("Staging");
        newRecord.setStatus("SUCCESS");
        newRecord.setCommitHash("c12345a");
        newRecord.setDeployedBy("Jenkins");
        newRecord.setDurationMillis(34000);

        DeploymentRecord saved = deploymentService.recordDeployment(newRecord);
        assertNotNull(saved.getId());
        assertTrue(saved.getId().startsWith("DEP-"));
        assertEquals("1.0.1", saved.getVersion());

        // Verify it is in all deployments
        Optional<DeploymentRecord> found = deploymentService.getDeploymentById(saved.getId());
        assertTrue(found.isPresent());
    }

    @Test
    @DisplayName("Should return all registered services")
    void testGetAllServices() {
        Collection<ServiceStatus> services = deploymentService.getAllServices();
        assertNotNull(services);
        assertTrue(services.size() >= 4);

        boolean hasTomcat = services.stream().anyMatch(s -> s.getName().equals("DevOps-Flow-App"));
        boolean hasJenkins = services.stream().anyMatch(s -> s.getName().equals("Jenkins-CI-CD"));
        boolean hasNexus = services.stream().anyMatch(s -> s.getName().equals("Nexus-Repository"));
        boolean hasSonar = services.stream().anyMatch(s -> s.getName().equals("SonarQube-Server"));

        assertTrue(hasTomcat);
        assertTrue(hasJenkins);
        assertTrue(hasNexus);
        assertTrue(hasSonar);
    }

    @Test
    @DisplayName("Should register or update a service")
    void testRegisterService() {
        ServiceStatus customService = new ServiceStatus("Trivy-Scanner", "0.50.0", "UP", "trivy-host", 0, 3600, "15ms");
        deploymentService.registerService(customService);

        Collection<ServiceStatus> services = deploymentService.getAllServices();
        assertTrue(services.stream().anyMatch(s -> s.getName().equals("Trivy-Scanner")));
    }

    @Test
    @DisplayName("Should produce comprehensive system telemetry map")
    void testGetSystemTelemetry() {
        Map<String, Object> telemetry = deploymentService.getSystemTelemetry();

        assertNotNull(telemetry);
        assertEquals("UP", telemetry.get("status"));
        assertEquals("WAR (Web Application Archive)", telemetry.get("packaging"));
        assertEquals("Apache Tomcat", telemetry.get("targetServer"));
        assertTrue(telemetry.containsKey("uptimeSeconds"));
        assertTrue(telemetry.containsKey("availableProcessors"));
        assertTrue(telemetry.containsKey("usedMemoryMB"));
        assertTrue(telemetry.containsKey("pipelineStages"));
        assertTrue(telemetry.containsKey("successRatePercent"));
    }
}
